version: '3'
services:
 mongo:
  image: mongo
  volumes:
   - /data/mongodb/db:/data/db
  ports:
   - "27017:27017"


 api:
  build: .
  command: node app.js
  volumes:
   - .:/fixit-app
  ports:
   - "3000:3000"
  links:
   - mongo

#server:
#  build: ../fixit-app/
 # command: node app.js
  #ports:
   #- "3000:3000"
#  links:
#   - mongo

#client:
# build: ../fixit-app/
# command: npm start
# ports:
#  - "4200:4200"
# links:
#  - server


